<a href="https://colab.research.google.com/github/dheerajsk26/Personal_Notes/blob/main/Numpy_Practice.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **NumPy Practice**
---



In [ ]:
#installing numpy library

pip install numpy

In [ ]:
#checking whether the library is installed

try:
    import numpy
    print('numpy is installed.')
except ImportError:
    print('numpy is not installed.')


numpy is installed.


In [ ]:
#checking the current version of numpy library

import numpy as np
print(np.__version__)

2.0.2


In [ ]:
import pandas as pd
print(pd.__version__)

2.2.2


### Difference between Python list and NumPy array
---



In [ ]:
import numpy as np

list1 = [1, 2, 3, 4]

#converting list to array using np.array
arr = np.array(list1)


print(list1)    #list is comma separated
print(arr)      #array is space separated

[1, 2, 3, 4]
[1 2 3 4]


In [ ]:
type(arr)

numpy.ndarray

In [ ]:
#issue with list data type, it gives concatenated list
a = [1, 2, 3]
b = [4, 5, 6]

# You can't do this:
a + b   #gives concatenation

[1, 2, 3, 4, 5, 6]

In [ ]:
#with NumPy
#Key idea: NumPy does element-wise operations

import numpy as np

a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

a + b   # [5 7 9]

array([5, 7, 9])

# **Creation of different types of arrays**
---



In [ ]:
# 1D array

list1 = [1, 2, 3, 4]
arr1 = np.array(list1)

np.array(list1)

# 2D array (matrix)
list2 = [4,3,2,1]
arr2 = np.array([list1,list2])


#3D array
list3 = [7,8,9,10]
arr3 = np.array([[list1,list2,list3]])


print(arr1)
print(arr2)
print(arr3)

[1 2 3 4]
[[1 2 3 4]
 [4 3 2 1]]
[[[ 1  2  3  4]
  [ 4  3  2  1]
  [ 7  8  9 10]]]


# **Attributes of Array**
---



In [ ]:
# Attributes of Array (properties of array)

print("Shape of arr1", arr1.shape)
print("Shape of arr2", arr2.shape)

print("Size of arr1", arr1.size)
print("Size of arr2", arr2.size)

print("dType of arr1", arr1.dtype)
print("dType of arr2", arr2.dtype)

print("n_dim of arr1", arr1.ndim)
print("n_dim of arr2", arr2.ndim)


Shape of arr1 (4,)
Shape of arr2 (2, 4)
Size of arr1 4
Size of arr2 8
dType of arr1 int64
dType of arr2 int64
n_dim of arr1 1
n_dim of arr2 2


In [ ]:
#creation of arrays

import numpy as np

a = np.zeros((2,3))     # all 0s
b = np.ones((2,2))      # all 1s
c = np.eye(3)           # identity matrix
d = np.empty(2)         #empty array with 2 elements
e = np.arange(8)        #an array with range of elements
f = np.linspace(0,2,5)  # 5 equal intervals
g = np.full((2,2), 5)   #identity elements in the whole array
z = np.arange(0,100,5)

# print(a)
# print(b)
# print(c)
# print(d) #python will put some random values in the array
# print(e)
# print(f)
# print(g)
print(z)


[ 0  5 10 15 20 25 30 35 40 45 50 55 60 65 70 75 80 85 90 95]


In [ ]:
import numpy as np
import random

s = random.randint(0,9)
print(s)

#random values array - float values
# r_arr = np.random.rand(2,2)
# print(r_arr)


#random values array - int values
r_arr1 = np.random.randint(1,100,(2,2))
print(r_arr1)

0
[[69 76]
 [64 47]]


# **Indexing and Slicing**
---
> Indexing: Accessing individual characters in a string. using their index

> Slicing: Accessing a portion of sequence using their indices




In [ ]:
import numpy as nd
s = [ 1,2,3,4,5]
x = np.array(s)

print(x)

#index value
print(x[1])

#negative index value
print(x[-1])

[1 2 3 4 5]
2
5


In [ ]:
#slicing
#array[start:stop:step]


#slicing first 3 elements
print(x[0:3])

#slicing last 3 elements
print(x[-3:])

#slicing middle 3 elements
print(x[1:4])

#slicing with step size-2
print(x[0:5:2])



[1 2 3]
[3 4 5]
[2 3 4]
[1 3 5]


In [ ]:
#indexing 2D arrays


print(arr2)

#accessing first row
print(arr2[1])

#accessing first element
print(arr2[1:])

#accessing elements of 4th column
print(arr2[:,3])

[[1 2 3 4]
 [4 3 2 1]]
[4 3 2 1]
[[4 3 2 1]]
[4 1]


**#Array Reshaping and Flattening**
---



In [ ]:
arr1

array([1, 2, 3, 4])

In [ ]:
#reshaping 1D array to 2D array

arr_r1 = arr1.reshape((4,1))

arr_r1

array([[1],
       [2],
       [3],
       [4]])

In [ ]:
arr2

array([[1, 2, 3, 4],
       [4, 3, 2, 1]])

In [ ]:
arr_r2 = arr2.reshape((4,2))

arr_r2

array([[1, 2],
       [3, 4],
       [4, 3],
       [2, 1]])

In [ ]:
#flattening

arr_f2 = arr2.flatten()

arr_f2

array([1, 2, 3, 4, 4, 3, 2, 1])

# **Array Stacking and Splitting**
---



In [ ]:
#creating a new array fro an existing array

v = np.array([1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

arr_v = v[3:8]
arr_v

array([4, 5, 6, 7, 8])

In [ ]:
#vertical and horizontal stacking

import numpy as np

a = np.array([1,2,3,4])
b = np.array([5,6,7,8])

print(np.vstack((a,b)))
print(np.hstack((a,b)))



[[1 2 3 4]
 [5 6 7 8]]
[1 2 3 4 5 6 7 8]


In [ ]:
c = np.array([[1,2,3],[4,5,6]])
c


array([[1, 2, 3],
       [4, 5, 6]])

In [ ]:
#horizontal splitting

h_split = np.hsplit(c,3)

for s in h_split:
  print(s)

[[1]
 [4]]
[[2]
 [5]]
[[3]
 [6]]


In [ ]:
#vertical splitting

v_split = np.vsplit(c,2)

for s in v_split:
  print(s)

[[1 2 3]]
[[4 5 6]]


In [ ]:
#transpose

arr = np.arange(6).reshape((2, 3))
arr

arr.transpose()

array([[0, 3],
       [1, 4],
       [2, 5]])

**# Mathematical Operation on Arrays**
---



In [ ]:
print(a+10) #addition
print(a-1)  #subtraction
print(a*2)  #multiplication
print(a/10) #division

[11 12 13 14]
[0 1 2 3]
[2 4 6 8]
[0.1 0.2 0.3 0.4]


In [ ]:
j = np.array([1,4,9])

j_sqr = np.sqrt(j)
print(j_sqr)   #square root

j_sqs = np.square(j)
print(j_sqs)   #square

[1. 2. 3.]
[ 1 16 81]


In [ ]:
a

array([1, 2, 3, 4])

In [ ]:
b

array([5, 6, 7, 8])

In [ ]:
#dot product

print(np.dot(a,b))

70


In [ ]:
#Statistical operations

print(np.mean(a))
print(np.median(a))
print(np.std(a))
print(np.min(a))
print(np.max(a))


2.5
2.5
1.118033988749895
1
4


In [ ]:
#Array comparison

k = np.array([1,2,3,4])
l = np.array([1,2,3,4])

print(np.array_equal(k,l))

True


In [ ]:
#unique values

p = np.array([11, 11, 12, 13, 14, 15, 16, 17, 12, 13, 11, 14, 18, 19, 20])

print(p)
unique_values = np.unique(p)
print(unique_values)

[11 11 12 13 14 15 16 17 12 13 11 14 18 19 20]
[11 12 13 14 15 16 17 18 19 20]


In [ ]:
#filtering

arr = np.array([1,2,3,4,5])
arr[arr > 2]

array([3, 4, 5])

# **Broadcasting**

---
> operation between an array and a single number or between arrays of two different sizes

> Broadcasting is a mechanism that allows NumPy to perform operations on arrays of different shapes.



In [ ]:
a*5

array([ 5, 10, 15, 20])

In [ ]:
a = np.array([1,2,3])
b = np.array([5])

print(a+b)

[6 7 8]


# **Saving and Loading an array**
---



In [ ]:
#saving an array

a = np.array([1,2,3])
print(a)
np.save('my_array', a)

[1 2 3]


In [ ]:
#loading an array

loaded_arr = np.load("my_array.npy")
print(loaded_arr)

[1 2 3]


**View and Copy**
---






In [ ]:
#creating view of an array -- shallow copy

c = np.array([1,2,3])
b = c

b[0] = 10
print(c)   # [10 2 3]  ← changed!

[10  2  3]


In [ ]:
#copying an array -- deep copy

d = b.copy()

array([10,  2,  3])

In [ ]:
d[0] = 5

print(b)
print(d)

[10  2  3]
[5 2 3]
